### ISSUE TITLE
Update copyright

### ISSUE THREAD

**Issue by jisungbin** [duckie-team/quack-quack-android#198]
```
Designed and developed by 2022 SungbinLand, Team Duckie

Licensed under the MIT.
Please see full license: https://github.com/sungbinland/quack-quack/blob/main/LICENSE
// out-of-date, referenced old organization and repository name
```

**Comment by jisungbin** [comment]
@EvergreenTree97 or @limsaehyun 엄청 간단한건데 시간 투자 가능하신 분? 👀

**Comment by EvergreenTree97** [comment]
.idea 수정 건인가요?

**Comment by jisungbin** [comment]
> .idea 수정 건인가요?

@EvergreenTree97 넵! 그것도 포함하고 프로젝트 전체 범위로 `https://github.com/sungbinland/quack-quack/blob/main/LICENSE` 부분을 `https://github.com/duckie-team/duckie-quack-quack/blob/main/LICENSE` 으로 바꾸면 될 거 같아요! (find & replace 기능 이용)

**Comment by EvergreenTree97** [comment]
넵 제가 지금 할게요

**Comment by jisungbin** [comment]
> 넵 제가 지금 할게요

감사합니다!

**Comment by jisungbin** [comment]
## DONE

https://github.com/duckie-team/duckie-quack-quack/pull/204

**Comment by jisungbin** [comment]
## Reopen

일부 라이선스 주소가 잘못됨

**Comment by jisungbin** [comment]
## 포기

#400
