### ISSUE TITLE
buildAnnotatedString 를 활용하는 컴포저블 추가 요청

### ISSUE THREAD

**Issue by riflockle7** [duckie-team/quack-quack-android#334]
`buildAnnotatedString` 를 활용하는 Composable 관련하여 기능 추가를 요청드립니다. 🙇

## 1. 일부 텍스트의 "폰트 굵기"만 변경 가능한 컴포넌트 필요
특정 텍스트의 `밑줄 처리`와 `색상`을 바꿔주는 Composable 은 있지만(ex. QuackUnderlineHeadLine2), 
`폰트 굵기`만 바꿔주는 Composable 은 없는 것 같습니다.
<img width="319" alt="image" src="https://user-images.githubusercontent.com/13694046/198117996-7fe1d70f-770c-499f-87e4-c680828c4c04.png">

> 기대결과 : 위의 "**targetUserId** 님이 내 글에 **새 댓글**을 달았어요" 처럼 만들 수 있어야 합니다.

## 2. 부분 텍스트 "클릭 이벤트 처리" 필요

![image](https://user-images.githubusercontent.com/13694046/198118383-1781bea8-8dd2-4474-a61b-6128310e41fa.png)

> 기대결과 : 부분 텍스트에 클릭 이벤트가 들어갈 수 있도록 처리가 필요합니다.

참고 : [관련 레퍼런스](https://stackoverflow.com/questions/65567412/jetpack-compose-text-hyperlink-some-section-of-the-text) 는 있는 것 같습니다.

**Comment by jisungbin** [comment]
참고 레퍼런스에 있는 `ClickableText` 를 사용하여 구현하는 방법은 제가 예전에 도로님께 말씀 드렸지만, 모종의 이유로 구현이 안됐던걸로 기억합니다. 아무쪼록 참고 자료 감사합니다! 11월 내로 꽥꽥 전체 리팩토링 하면서 미구현 컴포넌트 추가할 예정입니다.

**Comment by riflockle7** [comment]
어 플랫폼간 이슈가 있을까요? 되는 것 같았어서요 ㅇㅅㅇ

**Comment by jisungbin** [comment]
> 어 플랫폼 버전 이슈가 있을까요? 되는 것 같았어서요 ㅇㅅㅇ

저도 당연히 될거라 생각하고 도로님께 전달 드렸었지만,,,, 도로님이 어떻게 구현해보셨던건진 모르겠습니다
