### ISSUE TITLE
생성된 Baseline Profile에서 라이브러리에 해당하는 부분만 남기기

### ISSUE THREAD

**Issue by workspace** [duckie-team/quack-quack-android#369]
안녕하세요. 
얼마 전 baseline 도입을 마치고, 더 좋은 활용을 탐구하다가 @jisungbin 님께서 사례 공유를 해주셔서 의견을 하나 더해보고자 이슈를 남깁니다.

바로 생성된 baseline-prof.txt에서 모듈에 해당하는 부분만 남기는게 맞지 않냐는 의문이었습니다!
이미 아실 것 같지만, Jetpack 라이브러리들은 대부분 baseline-prof.txt가 생성되어있는데 라이브러리에 해당하는 부분만 남아있습니다. 이걸 어떻게 달성하는지 고민을 해봤는데 그냥 생성된 baseline-prof.txt를 src/main으로 옮길 때 패키지로 필터링을 해주면 되겠다는 아이디어가 떠올랐습니다.

덧붙여,
~공식 가이드는 app단에서 사용자의 여정에 따라 baseline-prof.txt를 수집하는 TopDown(?) 방식이 소개되어있지만, 저는 사용하는 라이브러리에서 제공을 해주는 BottomTop(?) 방식이 더 맞다는 생각이 들었어요.~ (생각해보니 목적이 다르다는 생각이 들어 줄 그었습니다😅) 그래서 저는 디자인 시스템과 ui core 정도에서 baseline-prof을 제공하면 앱 전반적으로  baseline prof의 효용을 누리지 않을까 생각이 들었습니다. 그런 점에서 quackquack의 사례가 반갑습니다. 

변경사항에 대한 설명은 pr에 적어두겠습니다!

**Comment by workspace** [comment]
레퍼런스를 찾다보니 아래와 같이 그냥 와일드카드?(*)를 활용하는 것으로 목적을 달성할 수 있다면 굳이 generate를 해야하나 생각도 드네요.
<img width="610" alt="image" src="https://user-images.githubusercontent.com/7759511/202336294-cd2bb091-91cc-4619-b2ab-b1ca35c51f9e.png">

**Comment by workspace** [comment]
gdg slack에 baseline profile에 대해 이야기하는 스레드가 하나 있는데, 그곳에서 wildcard에 대해 적혀있는 초기 commit을 보게 되어 공유 드립니다.
https://android-review.googlesource.com/c/platform/frameworks/support/+/1728275

고로 라이브러리는 wildcard를 통해 별도 generate 과정 없이 baseline-prof.txt를 작성하면 되지 않을까 생각해봅니다.
앱을 위한 baseline-prof는 무언가 알 수 없는 써드 파티들이 껴들어오니 benchmark를 통한 baseline-prof 생성이 필요할 것 같구요.

**Comment by jisungbin** [comment]
안녕하세요 workspace 님.

> 바로 생성된 baseline-prof.txt에서 모듈에 해당하는 부분만 남기는게 맞지 않냐는 의문이었습니다!
> ...
> ~ 생성된 baseline-prof.txt를 src/main으로 옮길 때 패키지로 필터링을 해주면 되겠다 ~

훌륭한 통찰과 그에 따른 아이디어 제시 감사합니다.

baseline profiles 를 제대로 도입하기 위해 기초적인 설정만 해둔 현재 시점에서는 차마 말씀해 주신 부분까지는 제가 고려하지 못했던거 같습니다.

또한 마지막에 첨부해주신 초기 커밋도 정말 큰 도움이 되었습니다.

꽥꽥 프로젝트에 관심을 갖고 기여해 주셔서 감사합니다.
