### ISSUE TITLE
컴포넌트 추상화에 대한 질문

### ISSUE THREAD

**Issue by EvergreenTree97** [duckie-team/quack-quack-android#375]
### 예시
![image](https://user-images.githubusercontent.com/70064912/202843669-1110d701-d7ee-4085-bd7c-d429fb10f11a.png)

- 기존 Component
`QuackRoundImage`

- 변경 후
`QuackImage(modifier = Modifier.clip(RoundCorner)`

예시 이외에도, GridLayout에 header가 필요한 경우 index 처리를 통해 덕키 프로덕트 개발자가 처리를 해줘야함
Q. 이처럼 추상화 단계를 한단계 줄이고 개발자에게 디자인 권한을 위임한 것인지? 궁금합니다

**Comment by jisungbin** [comment]
해당 컴포넌트는 `shape` 인자가 있습니다!

**Comment by jisungbin** [comment]
## Close

https://sungbinland.slack.com/archives/C03CM18M529/p1668849343660079?thread_ts=1668813063.223839&cid=C03CM18M529
