### ISSUE TITLE
폰트 리소스 변경

### ISSUE THREAD

**Issue by limsaehyun** [duckie-team/quack-quack-android#379]
1. 폰트 굵기가 얇게 표시됨
2. `꽯`, `뷃`, `휉` 과 같이 잘 쓰이지 않는 글자를 사용하면 해당 글자가 제대로 표시되지 않음

**Comment by jisungbin** [comment]
## Context

https://sungbinland.slack.com/archives/C03CM18M529/p1668855726919269?thread_ts=1668813063.223839&cid=C03CM18M529

**Comment by jisungbin** [comment]
## Done

#421
