### ISSUE TITLE
ui-components 1.4.0 필요 사항

### ISSUE THREAD

**Issue by jisungbin** [duckie-team/quack-quack-android#384]
# 1.4.0

- [ ] QuackSwitch 추가
- [ ] QuackDialog 추가
- [x] ~~QuackLargeButton 에 fading edge 지원 추가~~ (불필요)
- [x] ~~#379  해결~~ (후순위)

## 참고

- https://sungbinland.slack.com/archives/C03THTE8D7W/p1666286001818869

**Comment by EvergreenTree97** [comment]
[Category에 사용되는 Medium Button](https://www.figma.com/file/PnDRGtMpBnxFKS1NEgAGpi/Duckie_MVP-V0.2?node-id=36%3A230&t=nRMPM3a5YKV5KYFi-0)
[필적 확인 문구 TextField](https://www.figma.com/file/PnDRGtMpBnxFKS1NEgAGpi/Duckie_MVP-V0.2?node-id=1006%3A1453&t=nRMPM3a5YKV5KYFi-4)

**Comment by EvergreenTree97** [comment]
[QuackTopAppBar](https://www.figma.com/file/PnDRGtMpBnxFKS1NEgAGpi/Duckie_MVP-V0.2?node-id=1068%3A1281&t=3X98X0vxkjt2TzMl-4)에서 leadingIcon nullable하도록 변경해야함

**Comment by EvergreenTree97** [comment]
QuackBasicTextField에서, modifier 속성에 Clickable이 적용되지 않음

**Comment by riflockle7** [comment]
[Quack___Button](https://www.figma.com/file/PnDRGtMpBnxFKS1NEgAGpi/Duckie_MVP-V0.2?node-id=303%3A654&t=bwsmR1VEGp4VZwHi-0) 에서 텍스트로만 이루어지고 ripple 도 적용되는 컴포넌트 필요

**Comment by riflockle7** [comment]
- QuackTagType.Grayscale 설정할 때 trailingText = null 인 케이스 필요

현재 QuackTagType.Grayscale 설정 시
<image src="https://user-images.githubusercontent.com/13694046/207928922-305ecec1-8f97-4b00-9efb-1c41b557759f.png" width=120>

레이아웃 범위 표시
<image src="https://user-images.githubusercontent.com/13694046/207928976-8c03ec5f-0e0c-4741-a28c-f74f3c465c89.png" width=120>

**Comment by riflockle7** [comment]
QuackTopAppBar 의 TrailingContent 에 custom Composable 들어갈 수 있도록 처리 필요

<img width="466" alt="image" src="https://user-images.githubusercontent.com/13694046/207930776-18bbcbd4-d481-4ed8-8956-83b256e20846.png">

**Comment by limsaehyun** [comment]
QuackDivider에 Modifier 인자 추가
https://sungbinland.slack.com/archives/C043MKB4TJN/p1671064157606799

**Comment by limsaehyun** [comment]
사라진 QuackShape 복구하기
https://sungbinland.slack.com/archives/C043MKB4TJN/p1671098195528299

**Comment by riflockle7** [comment]
QuackLargeButton 에 `trailingIcon` 기능 추가
<img width="502" alt="image" src="https://user-images.githubusercontent.com/13694046/208440328-d3193db2-cdbf-40c4-8435-b3a19520df3d.png">

**Comment by EvergreenTree97** [comment]
[QuackTopAppBar](https://www.figma.com/file/PnDRGtMpBnxFKS1NEgAGpi/Duckie_MVP-V0.2?node-id=1068%3A1281&t=3X98X0vxkjt2TzMl-4)에서 클릭 리플 범위가 부자연스러움(원형으로 변경 희망) 

https://user-images.githubusercontent.com/70064912/208720719-bb41caba-9c2e-4fd3-8f95-084e71ac8b7b.mp4

**Comment by jisungbin** [comment]
### [QuackTopAppBar](https://www.figma.com/file/PnDRGtMpBnxFKS1NEgAGpi/Duckie_MVP-V0.2?node-id=1068%3A1281&t=3X98X0vxkjt2TzMl-4)에서 클릭 리플 범위가 부자연스러움(원형으로 변경 희망)

원형 리플은 리플을 직접 깎아서 만들어야 하며, 제가 알기론 컴포즈에선 불가능합니다.
또한 해당 클릭 범위는 의도된 기능입니다

**Comment by jisungbin** [comment]
## Done
