### ISSUE TITLE
QuackMediumToggleButton에서 잘림 현상 발생

### ISSUE THREAD

**Issue by EvergreenTree97** [duckie-team/quack-quack-android#404]
`MediumButton.TextPadding`의 horizontal이 58.dp로 되어있어, Modifier로 Button의 크기가 축소될 때 영향을 주는 것이라고 예상
 
 사용 컴포넌트 피그마 링크 : https://www.figma.com/file/PnDRGtMpBnxFKS1NEgAGpi/Duckie_MVP-V0.2?node-id=36%3A230&t=ODbB7VS2hg8bfMdZ-4

**Comment by jisungbin** [comment]
해당 컴포넌트는 꽥꽥 디자인 시스템에 구현돼 있지 않습니다.

무효한 이슈로 판단하여 close 합니다.
