### ISSUE TITLE
덕질고사 디자인 시스템 필요 사항

### ISSUE THREAD

**Issue by EvergreenTree97** [duckie-team/quack-quack-android#406]
[Category에 사용되는 Medium Button](https://www.figma.com/file/PnDRGtMpBnxFKS1NEgAGpi/Duckie_MVP-V0.2?node-id=36%3A230&t=nRMPM3a5YKV5KYFi-0)
[필적 확인 문구 TextField](https://www.figma.com/file/PnDRGtMpBnxFKS1NEgAGpi/Duckie_MVP-V0.2?node-id=1006%3A1453&t=nRMPM3a5YKV5KYFi-4)

**Comment by jisungbin** [comment]
## Tracked as #407
