### ISSUE TITLE
QuackLargeButtonType.Border 와 QuackLargeButtonType.Fill 의 높이가 다른듯함

### ISSUE THREAD

**Issue by riflockle7** [duckie-team/quack-quack-android#414]
문제 만들기 2단계 UI 작업 중, 두개의 타입 높이가 다르게 보여지는 것을 확인했습니다.
아래 코드를 통해 테스트 해보았습니다.

```kotlin
Row(
    modifier = Modifier
        .fillMaxWidth()
        .padding(
            start = 20.dp,
            end = 20.dp,
            top = 12.dp,
            bottom = 20.dp,
        )
        .layoutId(BottomLayoutId),
    verticalAlignment = Alignment.CenterVertically,
) {
    // 임시저장 버튼
    QuackLargeButton(
        modifier = Modifier.weight(1f),
        text = "임시저장",
        type = QuackLargeButtonType.Border,
    ) {

    }

    Spacer(modifier = Modifier.width(8.dp))

    // 다음 버튼
    QuackLargeButton(
        modifier = Modifier.weight(1f),
        text = "다음",
        type = QuackLargeButtonType.Fill,
        enabled = false,
    ) {

    }
}
```

강제 높이 적용 없이 위 코드 그대로 사용하면 아래와 같이 높이가 다르게 나옵니다.
![image](https://user-images.githubusercontent.com/13694046/209462916-f845db5a-c83b-4837-a2a6-efaecce33627.png)

아래는 modifier 에 추가로 `height(44.dp)` 를 적용했을 때의 모습입니다.
![image](https://user-images.githubusercontent.com/13694046/209462858-9eead132-2daf-4e2e-90ab-7968cb3111ff.png)

추측으로는 아래 코드를 통해 `textPadding` 을 적용하면서, 높이가 다르게 적용되는 듯한데 일단 검토가 필요해보입니다.
https://github.com/duckie-team/quack-quack-android/blob/f79bf07d67a96863b8bafc85d1a66796278d01b5/ui-components/src/main/kotlin/team/duckie/quackquack/ui/component/button.kt#L97-L106

**Comment by jisungbin** [comment]
의도된 스팩으로 보입니다.
해당 컴포넌트는 덕키 메인 컴포넌트로, 덕질고사 컴포넌트와 세부 스팩이 다를 수 있습니다.

**Comment by jisungbin** [comment]
덕질고사 컴포넌트는 #407 에서 관리됩니다.

**Comment by riflockle7** [comment]
음 그러면 현재 스펙 상으로는 44dp 적용이 필요한 상황인데, 위와 같이 강제 높이 설정을 해줘도 무방할까요?

**Comment by riflockle7** [comment]
\+ 그리고 문의의 경우 `closed` 처리는, issue 작성자가 닫는 것이 이상적입니다.
(물론 작성자가 close 처리를 잊었다면 지금처럼 관리자가 해야 합니다.)

지금 같이 작성자가 아직 궁금한 내용이 다 풀리지 않았다면 해결된 상황이 아니기에
가급적 작성자가 닫는 게 좋아보입니다.

**Comment by riflockle7** [comment]
추가 논의 내용 : https://sungbinland.slack.com/archives/C03TJD0TWGK/p1671961570387509
