### ISSUE TITLE
문제 2단계 관련 수정 요청사항

### ISSUE THREAD

**Issue by riflockle7** [duckie-team/quack-quack-android#419]
**1. QuackBasic2TextField 에서 drawAnimatedLine 선택적으로 적용하기**
    
QuackTextField (ex. QuackBasic2TextField) 에서 drawAnimatedLine 이 필수로 실행되어 선이 필요없는 스펙에서도 선이 나오고 있습니다.
![image](https://user-images.githubusercontent.com/13694046/211128568-c49449e7-bdea-4d3b-a5be-e505a0edff04.png)

선을 optional 하게 줄 수 있으면 좋을 것 같습니다.
    
----
    
**2. QuackDropDownCard border 선택 적용하기**
    
![image](https://user-images.githubusercontent.com/13694046/211128603-4c2574a0-6ece-4445-841d-b763806ee9af.png)
    
QuackDropDownCard 도 위와 마찬가지로 border 를 선택으로 적용할 수 있으면 좋을 것 같습니다.

**Comment by jisungbin** [comment]
## Done

추가됐습니다. 1.4.4 에 반영됩니다.
