### ISSUE TITLE
QuackAnnotatedHeadLine2 추가

### ISSUE THREAD

**Issue by limsaehyun** [duckie-team/quack-quack-android#442]
QuackAnnotated는 현재 Body2만 제공
QuackAnnotatedHeadLine2 로 필요함

<img width="354" alt="image" src="https://user-images.githubusercontent.com/80076029/215243388-05332159-815d-40a9-8b11-6576de6a91fd.png">

**Comment by jisungbin** [comment]
## Done

`2.0.0-alpha01`에 포함되었습니다.
