### ISSUE TITLE
QuackDialog 중앙정렬 기능 제공 필요

### ISSUE THREAD

**Issue by riflockle7** [duckie-team/quack-quack-android#460]
현재 최하단에만 Dialog 가 적용됨

![image](https://user-images.githubusercontent.com/13694046/219899245-1fb88f82-7dfc-4601-aeb0-73052523cb3e.png)

Dialog 가 중앙으로 배치될 수 있도록 기능 제공 필요

**Comment by jisungbin** [comment]
저게 OS에 의존 있던 걸로 기억...
각각 기기마다 dialog의 alignment가 다르더라구요

**Comment by jisungbin** [comment]
## Tracked by https://github.com/duckie-team/quack-quack-android/issues/791
