### ISSUE TITLE
QuackSingeLazyRowTag 에서 `tagType=QuackTagType.Grayscale(trailingText="")` 일 때 우측 패딩 제거 필요

### ISSUE THREAD

**Issue by riflockle7** [duckie-team/quack-quack-android#466]
꽤 묵혔던 이슈네요 제보한다고 해놓고 깜빡했어요~ 🙏 

<img width="168" alt="image" src="https://user-images.githubusercontent.com/13694046/220916899-c4b19d23-f836-4e11-b2f4-8b104a8f498e.png">

실제로 UI layout 구조를 보면 이렇습니다. 빈 값일 경우 아래 네모가 없어져야 될 것 같습니다.

<img width="212" alt="image" src="https://user-images.githubusercontent.com/13694046/220917386-a16f2684-12a3-4d0a-9648-dc2befda06c6.png">

**Comment by jisungbin** [comment]
악 제보 감사합니다

**Comment by jisungbin** [comment]
#691
