### ISSUE TITLE
QuackGrayscaleTextField textCount 기능 범용화 필요

### ISSUE THREAD

**Issue by riflockle7** [duckie-team/quack-quack-android#469]
QuackGrayscaleTextField 뿐만 아니라 
흰색 배경의 입력창이라거나, 여러줄의 글을 쓰는 TextField (ex. QuackReviewTextArea) 의 경우에도 
textCount 체크가 필요합니다.

(`QuackGrayscaleTextField` 의 maxLength, showCounter 참고바랍니다.)

**Comment by jisungbin** [comment]
딱 이게 제가 1.x.x에서 말했던 문제네여

**Comment by riflockle7** [comment]
<img width="491" alt="image" src="https://user-images.githubusercontent.com/13694046/220960817-8b344fd7-87e9-4b5d-88f9-c83394c77ae7.png">

**Comment by jisungbin** [comment]
yes,,, 디자인 시스템을 처음 개발해봐서 이런 케이스까진 고려하질 못 했습니다 😢
