### ISSUE TITLE
덕키에서 꽥꽥으로 이전해야 할 컴포저블

### ISSUE THREAD

**Issue by EvergreenTree97** [duckie-team/quack-quack-android#485]
Source Code : [DuckieGridLayout](https://github.com/duckie-team/duckie-android/blob/develop/shared-ui-compose/src/main/kotlin/team/duckie/app/android/shared/ui/compose/DuckieGridLayout.kt)
Figma : https://www.figma.com/file/PnDRGtMpBnxFKS1NEgAGpi/Duckie_MVP-V0.2?node-id=36%3A230&t=ja8D4T1M3CEKL8Ml-4
![image](https://user-images.githubusercontent.com/70064912/223116578-7a3f4483-6e9d-441d-92f1-f63efd7d41fe.png)

**Comment by EvergreenTree97** [comment]
Source Code : [FlowLayout](https://github.com/duckie-team/duckie-android/blob/develop/shared-ui-compose/src/main/kotlin/team/duckie/app/android/shared/ui/compose/FlowLayout.kt)

Figma : https://www.figma.com/file/PnDRGtMpBnxFKS1NEgAGpi/Duckie_MVP-V0.2?node-id=3458%3A4451&t=ja8D4T1M3CEKL8Ml-4

![image](https://user-images.githubusercontent.com/70064912/223117591-f625fd90-b2ab-4e0c-8229-ebf264a5c961.png)

**Comment by limsaehyun** [comment]
Source Code : [Dialog](https://github.com/duckie-team/duckie-android/blob/develop/shared-ui-compose/src/main/kotlin/team/duckie/app/android/shared/ui/compose/Dialog.kt)

Figma : https://www.figma.com/file/PnDRGtMpBnxFKS1NEgAGpi/Duckie_MVP-V0.2?node-id=4304-10933&t=9Fd7ifi5llfFbW6a-4

**Comment by jisungbin** [comment]
@EvergreenTree97 @limsaehyun 감사합니다.

**Comment by jisungbin** [comment]
## Tracked by #791
